fix : github action node version

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -33,6 +33,23 @@ jobs:
             git fetch origin main
             git reset --hard origin/main
 
+            echo "===> Load NVM"
+            export NVM_DIR="$HOME/.nvm"
+            if [ -s "$NVM_DIR/nvm.sh" ]; then
+              . "$NVM_DIR/nvm.sh"
+            else
+              echo "NVM not found at $NVM_DIR"
+              exit 1
+            fi
+
+            echo "===> Install and use Node.js 22"
+            nvm install 22
+            nvm use 22
+
+            echo "===> Show Node and NPM version"
+            node -v
+            npm -v
+
             echo "===> Install PHP dependencies"
             composer install --no-dev --optimize-autoloader --no-interaction
 
